version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: gestion-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: gestion-frontend
    ports:
      - "8080:80"
    restart: always
